version: '3'

vars:
  BINARY_NAME: fire-flow
  MAIN_PATH: ./cmd/fire-flow
  BUILD_DIR: ./bin

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-tools:
    desc: Install development tools
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  kestra-start:
    desc: Start Kestra server
    cmds:
      - kestra server start

  kestra-version:
    desc: Show Kestra version
    cmds:
      - kestra --version

  build:
    desc: Build the application
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - '{{.BUILD_DIR}}/{{.BINARY_NAME}}'

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - '{{.BUILD_DIR}}/{{.BINARY_NAME}}'

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linters
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run ./... || true

  tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy
      - go mod verify

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: tidy
      - task: lint
      - task: test
